import java.time.LocalDate
import java.time.format.DateTimeFormatter
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
    id 'kotlin-kapt'
    id("com.google.dagger.hilt.android")
    id("kotlin-parcelize")
    id 'com.google.firebase.crashlytics'
    id 'org.jetbrains.kotlin.plugin.compose' version '2.2.21'
    id 'kotlinx-serialization'
}

def getCurrentGitBranch() {
    def gitBranch = "default"
    try {
        def workingDir = new File("${project.projectDir}")
        def result = 'git rev-parse --abbrev-ref HEAD'.execute(null, workingDir)
        result.waitFor()
        if (result.exitValue() == 0) {
            gitBranch = result.text.trim()
        }
    } catch (e) {
    }
    return gitBranch
}

android {
    signingConfigs {
        qa {
            storeFile file('qa_key.jks')
            storePassword System.getenv("STAGING_PASSWORD")
            keyPassword System.getenv("STAGING_PASSWORD")
            keyAlias System.getenv("STAGING_ALIAS")
        }
    }
    namespace 'org.easydictionary.app'
    compileSdkVersion 36

    defaultConfig {
        applicationId "org.easydictionary.app"
        minSdk 24
        targetSdk 36
        versionCode 5
        versionName "0.4"

        signingConfig signingConfigs.debug
        testInstrumentationRunner = "org.easydictionary.app.test.DictionaryHiltTestRunner"
    }

    buildTypes {
        debug {
            buildConfigField "String", "FIREBASE_DATABASE_URL", "\"https://easy-dictionary-b003d-default-rtdb.europe-west1.firebasedatabase.app/\""
            buildConfigField "String", "SECURE_KEY_ALIAS", "\"debug_secure_key_alias\""
            buildConfigField "String", "BASE_API_URL", "\"http://dev.easydictionary.org/api/\""
            buildConfigField "String", "LANGUAGES_BASE_API_URL", "\"https://languages.dictionaryeasy.workers.dev/\""
            buildConfigField "String", "WORD_TYPES_BASE_API_URL", "\"https://word-types.dictionaryeasy.workers.dev/\""
            buildConfigField "String", "PHONETICS_BASE_API_URL", "\"https://phonetics.dictionaryeasy.workers.dev/\""
        }
        release {
            buildConfigField "String", "FIREBASE_DATABASE_URL", "\"https://easy-dictionary-b003d-default-rtdb.europe-west1.firebasedatabase.app/\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    flavorDimensions += "version"
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
        freeCompilerArgs = ['-XXLanguage:+PropertyParamAnnotationDefaultTargetMode']
    }
    packagingOptions {
        resources.excludes.add("META-INF/*")
    }
    buildFeatures {
        compose true
    }
}
kapt { correctErrorTypes = true }

dependencies {
    //core
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.4")
    //dependency injections
    implementation("com.google.dagger:hilt-android:2.57.2")
    implementation 'androidx.test.ext:junit-ktx:1.3.0'
    implementation 'androidx.navigation:navigation-testing:2.9.5'
    kapt("com.google.dagger:hilt-android-compiler:2.57.2")
    //navigation
    implementation 'androidx.hilt:hilt-navigation-compose:1.3.0'
    implementation 'androidx.navigation:navigation-compose:2.9.5'
    //http
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.retrofit2:retrofit:3.0.0")
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    //ui
    implementation(platform("androidx.compose:compose-bom:2025.09.01"))
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended-android:1.7.8")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("io.coil-kt:coil-compose:2.7.0")
    implementation("io.coil-kt:coil-svg:2.7.0")
    implementation "androidx.compose.ui:ui-text-google-fonts:1.9.4"
    debugImplementation("androidx.compose.ui:ui-tooling")
    //firebase
    implementation platform('com.google.firebase:firebase-bom:34.3.0')
    implementation 'com.google.firebase:firebase-crashlytics:20.0.2'
    implementation 'com.google.firebase:firebase-analytics:23.0.0'
    //api
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0'
    //facebook
    implementation 'com.facebook.android:facebook-android-sdk:18.1.3'
    //ui
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    // Unit (JVM)
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
    testImplementation("io.mockk:mockk:1.14.6")
    testImplementation("com.google.truth:truth:1.4.5")
    testImplementation("app.cash.turbine:turbine:1.2.1")
    // Hilt instrumentation
    androidTestImplementation("com.google.dagger:hilt-android-testing:2.57.2")
    kaptAndroidTest("com.google.dagger:hilt-android-compiler:2.57.2")
    // UI tests (instrumentation)
    androidTestImplementation("androidx.test.ext:junit:1.3.0")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.7.0")
    androidTestImplementation("androidx.compose.ui:ui-test-junit4:1.9.4")
    debugImplementation("androidx.compose.ui:ui-test-manifest:1.9.4")
    androidTestImplementation("app.cash.turbine:turbine:1.2.1")
}

kapt {
    correctErrorTypes = true
}