import java.time.LocalDate
import java.time.format.DateTimeFormatter
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
    id 'kotlin-kapt'
    id("com.google.dagger.hilt.android")
    id("kotlin-parcelize")
    id 'com.google.firebase.crashlytics'
    id 'org.jetbrains.kotlin.plugin.compose' version '2.2.0'
    id 'kotlinx-serialization'
}

def getCurrentGitBranch() {
    def gitBranch = "default"
    try {
        def workingDir = new File("${project.projectDir}")
        def result = 'git rev-parse --abbrev-ref HEAD'.execute(null, workingDir)
        result.waitFor()
        if (result.exitValue() == 0) {
            gitBranch = result.text.trim()
        }
    } catch (e) {
    }
    return gitBranch
}

android {
    signingConfigs {
        qa {
            storeFile file('qa_key.jks')
            storePassword System.getenv("STAGING_PASSWORD")
            keyPassword System.getenv("STAGING_PASSWORD")
            keyAlias System.getenv("STAGING_ALIAS")
        }
    }
    namespace 'org.easydictionary.app'
    compileSdk 35

    defaultConfig {
        applicationId "org.easydictionary.app"
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName "0.4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        signingConfig signingConfigs.debug
    }

    buildTypes {
        debug {
            buildConfigField "String", "FIREBASE_DATABASE_URL", "\"https://easy-dictionary-b003d-default-rtdb.europe-west1.firebasedatabase.app/\""
            buildConfigField "String", "SECURE_KEY_ALIAS", "\"debug_secure_key_alias\""
            buildConfigField "String", "BASE_API_URL", "\"http://dev.easydictionary.org/api/\""
            buildConfigField "String", "LANGUAGES_BASE_API_URL", "\"https://languages.dictionaryeasy.workers.dev/\""
        }
        staging {
            signingConfig signingConfigs.qa
            buildConfigField "String", "FIREBASE_DATABASE_URL", "\"https://easy-dictionary-b003d-default-rtdb.europe-west1.firebasedatabase.app/\""
        }
        release {
            buildConfigField "String", "FIREBASE_DATABASE_URL", "\"https://easy-dictionary-b003d-default-rtdb.europe-west1.firebasedatabase.app/\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    flavorDimensions += "version"
    productFlavors {
        local {
            applicationIdSuffix = ".dev"
            versionNameSuffix = "-dev"
        }
        demo {
            dimension = "version"
            applicationIdSuffix = ".dev"
            versionNameSuffix = "-dev"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
    packagingOptions {
        resources.excludes.add("META-INF/*")
    }
    buildFeatures {
        compose true
    }
}

dependencies {
    //core
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.2")
    //dependency injections
    implementation("com.google.dagger:hilt-android:2.56.2")
    kapt("com.google.dagger:hilt-android-compiler:2.56.2")
    //navigation
    implementation 'androidx.navigation:navigation-ui-ktx:2.9.0'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.0'
    implementation 'androidx.hilt:hilt-navigation-compose:1.2.0'
    implementation 'androidx.navigation:navigation-compose:2.9.1'
    //http
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.retrofit2:retrofit:3.0.0")
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    //ui
    implementation(platform("androidx.compose:compose-bom:2024.06.00"))
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended-android:1.7.8")
    implementation("androidx.compose.foundation:foundation")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("io.coil-kt:coil-compose:2.7.0")
    implementation("io.coil-kt:coil-svg:2.7.0")
    debugImplementation("androidx.compose.ui:ui-tooling")
    //firebase
    implementation platform('com.google.firebase:firebase-bom:33.16.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-database-ktx'
    implementation 'com.google.firebase:firebase-crashlytics:19.4.4'
    implementation 'com.google.firebase:firebase-analytics:22.5.0'
    //api
    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0'
    //facebook
    implementation 'com.facebook.android:facebook-android-sdk:18.0.3'
    //ui
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    //tests
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

kapt {
    correctErrorTypes = true
}