name: Android Stage Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Decode keystore file
      id: decode_keystore
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'qa_key.jks'
        fileDir: './app/'
        encodedString: ${{ secrets.STAGING_ENCRYPTED_KEY_STORE }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:bundleDemoStaging
      env:
          STAGING_ALIAS: ${{ secrets.STAGING_ALIAS }}
          STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
    - name: upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.STAGING_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.STAGING_CREDENTIAL_FILE_CONTENT }}
        groups: Testers
        file: app/build/outputs/bundle/demoStaging/app-demo-staging.aab
