name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: base64-to-file
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'qa_key.jks'
          encodedString: ${{ secrets.STAGING_ENCRYPTED_KEY_STORE }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:bundleDemoStaging
      env:
          STAGING_ALIAS: ${{ secrets.STAGING_ALIAS }}
          STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
